name: build java using maven
on:   
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  get_code_into_machine:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install java on runner
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: build package
        run: mvn clean package
      - name: check the name of the jar file created
        run: find . -name "*.jar"
      - name: configure aws cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::995757496819:role/oidcrole
          aws-region: ap-south-1
      - name: copy the created jar file into s3 bcuket
        run: aws s3 cp target/my-java-app-1.0-SNAPSHOT.jar s3://${{ secrets.AWS_BUCKET }}/
      - name: Deploy and run JAR on EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --parameters 'commands=[
              "aws s3 cp s3://${{ secrets.AWS_BUCKET }}/my-java-app-1.0-SNAPSHOT.jar /home/ec2-user/app.jar",
              "java -jar /home/ec2-user/app.jar"
            ]' \
            --region ap-south-1
      
          
          
      
          
      
    
