name: build java using maven
on:   
  workflow_dispatch:
jobs:
  get_code_into_machine:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install java on runner
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: build package
        run: mvn clean package
      - name: check the name of the jar file created
        run: find . -name "*.jar"
      - name: enter into ssh via ec2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./target/my-java-app-1.0-SNAPSHOT.jar"
          target: "/jarfolder"
      
          
          
      
          
      
    
