name: build java using maven
on:   
  workflow_dispatch:
jobs:
  get_code_into_machine:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install java on runner
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: build package
        run: mvn clean package
      - name: check the name of the jar file created
        run: find . -name "*.jar"
      - name: configure aws cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1
      
          
          
      
          
      
    
